export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE"

export const CONFIRM_ORDER_REQUEST = "CONFIRM_ORDER_REQUEST"
export const CONFIRM_ORDER_SUCCESS = "CONFIRM_ORDER_SUCCESS"
export const CONFIRM_ORDER_FAILURE = "CONFIRM_ORDER_FAILURE"

export const PLACED_ORDER_REQUEST = "PLACED_ORDER_REQUEST"
export const PLACED_ORDER_SUCCESS = "PLACED_ORDER_SUCCESS"
export const PLACED_ORDER_FAILURE = "PLACED_ORDER_FAILURE"

export const DELIVERED_ORDER_REQUEST = "DELIVERED_ORDER_REQUEST"
export const DELIVERED_ORDER_SUCCESS = "DELIVERED_ORDER_SUCCESS"
export const DELIVERED_ORDER_FAILURE = "DELIVERED_ORDER_FAILURE"

export const SHIP_ORDER_REQUEST = "SHIP_ORDER_REQUEST"
export const SHIP_ORDER_SUCCESS = "SHIP_ORDER_SUCCESS"
export const SHIP_ORDER_FAILURE = "SHIP_ORDER_FAILURE"

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST"
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS"
export const CANCEL_ORDER_FAILURE = "CANCEL_ORDER_FAILURE"

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE"